uselagoon/machinery

api/lagoon/client/deployments.go

just a minor fix in order of operations on checking if a deployment exists in the returned data

fix: only set deployment if one exists

---

api/schema/environment.go
api/schema/logs.go

Part of https://github.com/uselagoon/lagoon/issues/2975
The remote-controller no longer sends `MonitoringURLs` so we can remove the reference in the `LagoonLogMeta` struct. 
Since machinery is an "internal" (to lagoon) tool and we are dropping monitoring urls, I removed it from `UpdateEnvironmentPatchInput` too. It could technically stay in so that machinery matches the API schema exactly, but I don't think that provides any benefits?

Remove MonitoringURLs support

---

api/lagoon/client/_lgraphql/tasks/uploadFilesForTask.graphql
api/lagoon/client/client.go
api/lagoon/client/lgraphql/lgraphql.go
api/lagoon/client/tasks.go
api/lagoon/tasks.go
api/schema/tasks.go

Simple PR to add support for uploading files to tasks. This is useful to make it easier for tasks to upload files using the Lagoon CLI or some other tool.

chore: add support for uploading files to tasks

---

api/lagoon/helpers.go
api/schema/deployment.go
api/schema/environment.go
api/schema/schema.go

Adds a helper function to validate the provided values are valid. Currently supports EnvironmentType & DeployType.

Feature: Type validation helper function

---

api/schema/project.go

Fixes an issue with using `ProjectByNameMetadata()` where it always returned an unmarshaling error from the `encoding/json` package.

Fix ProjectMetadata.Metadata type.

---

api/lagoon/client/deploytargets.go
api/lagoon/client/environments.go
api/lagoon/client/projects.go
api/lagoon/client/usergroups.go

Currently an error is returned when no results are found on a number of queries. This removes the return statement to allow for the CLI to handle any zero results cases.
Required for https://github.com/uselagoon/lagoon-cli/pull/301

change: remove error from queries with no results

---

api/lagoon/client/_lgraphql/environments/addOrUpdateStorageOnEnvironment.graphql
api/lagoon/client/client.go
api/lagoon/client/environments.go
api/lagoon/environments.go
api/schema/environment.go

Just marking the `bytesUsed` field as deprecated for now, `kibUsed` will be the new required input in the API in the future, but for now `bytesUsed` is still required by the API until the BC break is announced in a future release.

deprecate: environment storage bytesUsed for kiloBytesUsed

---

api/lagoon/client/_lgraphql/deployments/deployEnvironmentBranch.graphql
api/lagoon/client/_lgraphql/deployments/deployEnvironmentPromote.graphql
api/lagoon/client/_lgraphql/deployments/deployEnvironmentPullrequest.graphql
api/schema/deployment.go

This PR duplicates the logic for adding Build environment variables to deployments (branch, promote, and PR) in a similar fashion to what's currently [only](https://github.com/uselagoon/machinery/blob/v0.0.17/api/schema/deployment.go#L88) [found](https://github.com/uselagoon/machinery/blob/v0.0.17/api/lagoon/client/_lgraphql/deployments/deployEnvironmentLatest.graphql#L6) in the "deploy environment latest" API.
It simply enhances the mutations and the input structures.

Feature: Adds build variables to deploys: branch, promote, and pull request

---

api/lagoon/client/_lgraphql/notifications/projectNotificationEmail.graphql
api/lagoon/client/_lgraphql/notifications/projectNotificationMicrosoftTeams.graphql
api/lagoon/client/_lgraphql/notifications/projectNotificationRocketChat.graphql
api/lagoon/client/_lgraphql/notifications/projectNotificationSlack.graphql
api/lagoon/client/_lgraphql/notifications/projectNotificationWebhook.graphql

Updates relevant queries to request the `name` and `id` fields for all project notifications.
Required for https://github.com/uselagoon/lagoon-cli/pull/323

Change: Includes `name` and `id` for project notifications

---

utils/auth/html/response.html

The `close` button doesn't always close the tab due to browser security. This just simply removes the button and closing the browser tab or window is left to the user to perform. Sorry :'(

fix: remove close button from cli opener as it doesnt always work

---

api/lagoon/client/_lgraphql/environments/addOrUpdateStorageOnEnvironment.graphql

Fixes a bug in the mutation for `addOrUpdateStorageOnEnvironment` to use the right mutation name

fix: use the right mutation for the new storage update

---

api/lagoon/client/_lgraphql/environments/environmentById.graphql
api/lagoon/client/_lgraphql/environments/environmentByName.graphql
api/lagoon/client/_lgraphql/environments/environmentByNamespace.graphql
api/lagoon/client/_lgraphql/environments/environmentsByProjectName.graphql
api/lagoon/client/_lgraphql/environments/updateEnvironment.graphql
api/lagoon/client/client.go
api/lagoon/client/environments.go
api/lagoon/client/mutation_test.go

Just adding versioned requests to allow for times where the schema may add new return fields that aren't available in older versions.
This does change the `New` constructor to require a version of the API to be provided
example: https://github.com/uselagoon/lagoon-cli/pull/335

feat: add versioned requests to support changing schemas where possible

---

api/lagoon/client/notification.go

Just a quick one to fix the check for the organization id. Previously it was adding the organization field to the mutation if it was 0, but it should only do this if it is not 0

fix: negate organization id check

---

api/lagoon/client/_lgraphql/environments/deleteBackup.graphql
api/lagoon/client/environments.go
api/lagoon/environments.go
api/schema/backups.go

Just a quick one that allows the `backup-handler` in lagoon to be updated to use machinery

chore: add deletebackup mutation support

---

api/lagoon/client/_lgraphql/organizations/listOrganizationAdminsByName.graphql
api/lagoon/client/_lgraphql/usergroups/addAdminToOrganization.graphql
api/lagoon/client/_lgraphql/usergroups/usersByOrganization.graphql
api/schema/organization.go
api/schema/user.go

This adds a new command to list the administrators of an organization only.
Additionally, changes made to the `UsersByOrganization` to renamed `UsersByOrganizationID` and then a new `UsersByOrganizationName` which performs an organization name query first, then calls the `ID` query.
This makes it easier for tools to consume without having to do the double logic step that is currently done in the tools themselves. We could probably change more things that use `ID` as an input to do this (and still retain the `ID` versions). 
From an API side thing though in `uselagoon/lagoon` core, anywhere that `id` or `name` can be used to interact with something, we should definitely support both inputs where possible/makes sense in the future, and we can do this with deprecation or introduction of new …

feat: support for organization admins and adjustments to users

---

go.mod
go.sum
utils/cron/cron.go
utils/cron/cron_test.go

This can be used by other tools to ensure cronjob validations across Lagoon tools is consistent. Currently the `build-deploy-tool`, and soon `remote-controller` will be able to use this to validate cron schedules.

feat: add cron utility

---

api/lagoon/client/_lgraphql/projects/projectsByOrganizationName.graphql
api/lagoon/client/_lgraphql/projects/veryMinimalProjectByName.graphql
api/lagoon/client/deployments.go
api/lagoon/client/deploytargetconfigs.go
api/lagoon/client/environments.go
api/lagoon/client/projects.go
api/lagoon/client/tasks.go
api/lagoon/deployment.go
api/lagoon/deploytargetconfig.go
api/lagoon/environments.go
api/lagoon/projects.go
api/lagoon/tasks.go

A lot of queries in the API require the project ID, not the name. This is a work around to implement queries that support the name as an input instead of the ID by doing a `veryMinimalProjectByName` request before performing the actual query/mutation.
Previously the lagoon-cli would do a `minimalProjectByName` query before some requests to get the project ID without the user having to remember it, but this requests the `openshift` ID which organization owners currently can't see, so rather than break the query in machinery, this implements a new lightweight `veryMinimalProjectByName` which is internal to machinery only.
Ideally, the API would get updated to have `name` in requests instead of `id`, but this way when the API eventually does support it, these new functions can just be …

refactor: implement workaround for id replacement queries

---

api/lagoon/client/_lgraphql/environments/environmentById.graphql
api/lagoon/client/_lgraphql/environments/environmentByName.graphql
api/lagoon/client/_lgraphql/environments/environmentByNamespace.graphql
api/lagoon/client/_lgraphql/environments/environmentsByProjectName.graphql
api/lagoon/client/_lgraphql/environments/updateEnvironment.graphql
api/lagoon/client/client.go
api/lagoon/client/environments.go

Removes the api version checks (`apiVerGreaterThanOrEqual`) in several queries & `newVersionedRequest` as it's no longer required with their removal.

Change: Removes newVersionedRequest

---

api/lagoon/client/_lgraphql/projects/allProjects.graphql

Adds additional fields to `allProjects` to accomodate support for `--wide` flags.
Required for https://github.com/uselagoon/lagoon-cli/pull/434

Change: Adds additional fields to allProjects

---

api/lagoon/client/tasks.go

Just a quick fix for the invokable tasks query to use the right variables.

fix: correct variables for invokable tasks query

---

utils/sshtoken/sshtoken.go

If `sshtoken.RetrieveToken` is called with no private key, and no keys in an ssh agent, it will panic because `ssh.AuthMethod` can't have any `nil` values:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x82d9e1]
goroutine 1 [running]:
golang.org/x/crypto/ssh.(*connection).clientAuthenticate(0xc000128280, 0xc000134000)
~/go/pkg/mod/golang.org/x/crypto@v0.32.0/ssh/client_auth.go:99 +0x6e1
golang.org/x/crypto/ssh.(*connection).clientHandshake(0xc000128280, {0xc00035e8d0, 0x27}, 0xc000134000)
~/go/pkg/mod/golang.org/x/crypto@v0.32.0/ssh/client.go:113 +0x297
golang.org/x/crypto/ssh.NewClientConn({0xc40938, 0xc00012c008}, {0xc00035e8d0, 0x27}, 0xc00020f580) …
```

fix: panic when RetrieveToken finds no auth methods
